name: AutoDeploy

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install and Build
        run: |
          npm install
          npm run build
      
      - name: Upload Bundles
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          password: ${{ secrets.DC_PASS }}
          source: "./dist/*"
          target: /home/cj/citest/
      
      - name: Run a one-line script
        run: echo CI_DONE
